# Generated by Django 5.0.6 on 2024-07-16 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0006_remove_employer_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('location', models.CharField(max_length=100, verbose_name='مکان')),
                ('cooperation_type', models.CharField(choices=[('full_time', 'full_time'), ('part_time', 'part_time')], max_length=100, verbose_name='نوع همکاری')),
                ('minimum_expertise', models.CharField(choices=[('less 1 year', 'less 1 year'), ('between 1 and 3 years', 'between 1 and 3 years'), ('between 3 and 5 years', 'between 3 and 5 years'), ('more than 5 years', 'more than 5 years')], max_length=100, verbose_name='حداقل سابقه کار')),
                ('salary', models.PositiveIntegerField(verbose_name='حقوق')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('about_company', models.TextField(verbose_name='درباره شرکت')),
                ('required_skills', models.TextField(blank=True, null=True, verbose_name='مهارت های لازم')),
                ('military_service_status', models.CharField(blank=True, choices=[('end of service', 'end of service'), ('medical exemption', 'medical exemption'), ('permanent exemption', 'permanent exemption')], max_length=100, null=True, verbose_name='وضعیت سربازی')),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('both', 'both')], max_length=100, null=True, verbose_name='جنسیت')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.employer', verbose_name='شرکت')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(max_length=100, verbose_name='نام در url')),
                ('advertise', models.ManyToManyField(blank=True, to='EmployersApp.jobadvertisement', verbose_name='آگهی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EmployersApp.jobcategory', verbose_name='دسته بندی')),
            ],
        ),
    ]
