# Generated by Django 5.0.6 on 2024-07-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployersApp', '0003_jobadvertisement_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobadvertisement',
            name='created_at',
        ),
    ]
