version: '3.8'

services:
  redis:
    image: redis:7.0.11-alpine
    container_name: redis
    restart: always
    networks:
      - main

  django:
    image: job-django
    container_name: django
    build:
      context: ./code
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./code:/code/
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DEBUG=True
      - SECRET_KEY=sdlkfhsdlfhslhdslkdjfsldejfdsl@sldfhglsdfhg
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=infinite_job
      - POSTGRES_USER=main_admin
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_PORT=5432
    restart: always
    networks:
      - main
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=infinite_job
      - POSTGRES_USER=main_admin
      - POSTGRES_PASSWORD=12345678
    networks:
      - main
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - main

  celery:
    container_name: celery
    build:
      context: ./code
      dockerfile: Dockerfile
    command: celery --app=config.celery_base worker -l INFO -Q tasks -E -B
    volumes:
      - ./code:/code/
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DEBUG=True
      - SECRET_KEY=sdlkfhsdlfhslhdslkdjfsldejfdsl@sldfhglsdfhg
    restart: always
    depends_on:
      - redis
      - django
      - rabbitmq
    networks:
      - main

  flower:
    image: mher/flower
    container_name: flower
    ports:
      - "5555:5555"
    restart: always
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - celery
    networks:
      - main

networks:
  main:
    name: main
volumes:
  postgres_data:
    name: postgres_data
