# Generated by Django 5.0.6 on 2024-07-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test',
            field=models.BooleanField(default=False, verbose_name='test'),
        ),
    ]
