# Generated by Django 5.0.6 on 2024-07-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_customuser_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='test',
        ),
    ]
