# Generated by Django 5.0.6 on 2024-07-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_remove_customuser_test'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(blank=True, choices=[(1, 'مرد'), (2, 'زن')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
    ]
