# Generated by Django 5.0.6 on 2024-07-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود'),
        ),
    ]
