# Generated by Django 5.0.6 on 2024-07-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_employer_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='last_login',
        ),
    ]
