# Generated by Django 5.0.6 on 2024-07-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_remove_employer_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_employer',
            field=models.BooleanField(verbose_name='کارجو/شرکت'),
        ),
    ]
