# Generated by Django 5.0.6 on 2024-07-27 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmployersApp', '0004_alter_jobadvertisement_updated_at'),
        ('UserApp', '0008_alter_employer_user_alter_jobseeker_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'pending'), (1, 'accepted'), (2, 'rejected')], default=0, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployersApp.jobadvertisement', verbose_name='آگهی استخدام')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.jobseeker', verbose_name='درخواست کننده')),
            ],
            options={
                'db_table': 'apply_request',
            },
        ),
    ]
